[[oracle-java-code-conventions]]
= [Coding Style] Oracle Java编码规范

原文地址： http://www.cesclub.com/bw/jishuzhongxin/xiangmuyanfaguanli/2012/1002/42434.html
Oracle官方Java编码规范（英文版）： http://www.oracle.com/technetwork/java/codeconvtoc-136057.html

== 介绍(Introduction)
=== 为什么要有编码规范（Why Have Code Conventions）
编码规范对于程序员而言尤为首要，有以下几个原因：

- 一个软件的生命周期中，80％的花费在于维护
- 几乎没有任何一个软件，在其全部生命周期中，均由最初的开辟人员来维护
- 编码规范可以改良软件的可读性，可以让程序员尽快而彻底地理解新的代码
- 若是你将源码作为产品公布，就须要确任它是否被很好的打包并且清楚无误，一如你已构建的其它任何产品

为了履行规范，每个软件开辟人员必须一致遵守编码规范。

=== 版权声明（Acknowledgments）
本文档反应的是Sun MicroSystems公司，Java说话规范中的编码标准项目组。首要供献者包含：Peter King，Patrick Naughton，Mike DeMoney，Jonni Kanerva，Kathy Walrath以及Scott Hommel。
本文档现由Scott Hommel维护，有关评论定见请发至shommel@eng.sun.com


== 文件名（File Names）
这项目组列出了常用的文件名及后缀。

=== 文件后缀（File Suffixes）
Java程序应用下列文件后缀：
[width="50%",options="header"]
|=======
|文件类型 |文件后缀
|Java源文件 |.java
|Java字节码文件 |.class
|=======

=== 常用文件名（Common File Names）
常用的文件名包含：
[cols="2,8",options="header"]
|=======
|文件名 |用处
|GNUmakefile |makefiles的首选文件名。我们采取gnumake来构建（build）软件。
|README |概述特定目录下所含内容的文件的首选文件名
|=======


== 文件组织（File Organization）
一个文件由被空行分别而成的段落以及标识每个段落的可选注释共同构成。跨越2000行的程序难以浏览，应当尽量避免。
"<<_java_java_source_file_example,Java源文件示例>>"提供了一个合理组织的Java程序范例。


=== Java源文件（Java Source Files）
每个Java源文件都包含一个单一的公共类或接口。若私有类和接口与一个公共类相接洽关系，可以将它们和公共类放入同一个源文件。公共类必须是这个文件中的第一个类或接口。

Java源文件还遵守以下规矩：

- 开首注释（参考"<<__beginning_comments,首行注释>>"）
- 包和引入语句（参考"包和引入语句"）
- 类和接口声明（参考"类和接口声明"）

[[__beginning_comments]]
==== 首行注释（Beginning Comments）
所有的源文件都应当在文件开始有一个C语言风格的注释，包含类名、版本信息、日期和版权声明：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
/*
 * Classname
 *
 * Version information
 *
 * Date
 *
 * Copyright notice
 */
----

==== 包和引入语句（Package and Import Statements）
在多半Java源文件中，第一个非注释行是包语句。在它之后可以跟引入语句。例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
package java.awt;

import java.awt.peer.CanvasPeer;
----

==== 类和接口声明（Class and Interface Declarations）
下表描述了类和接口声明的各个项目组以及它们呈现的先后次序。参考"<<_java_java_source_file_example,Java源文件示例>>"中一个包含注释的例子。
[cols="1,4,8",options="header"]
|======
||类/接口声明的各项目组|注解
|1|类/接口文档注释（`/**……*/`）|该注释中所需包含的信息，参考"<<__documentation_comments,文档注释>>"
|2|类或接口的声明|
|3|类/接口的注释（`/*……*/`）若是有须要的话|该注释应包含任何有关全部类或接口的信息，而这些信息又不合适作为类/接口文档注释。
|4|类的（静态）变量|先是类的公共变量，随后是维护变量，再后是包一级此外变量（没有访问控制修饰符，access modifier），最后是私有变量。
|5|实例变量|先是公共级，随后是维护级，再后是包一级（没有访问控制修饰符），最后是私有级。
|6|构造函数|
|7|方法|这些方法应当按功能，而非感化域或调用权限，分组。例如，一个私有的类方法可以置于两个公有的实例方法之间。其目标是为了更便于浏览和理解代码。
|======

== 缩进排版（Indentation）
缩进排版一般使用4个空格作为一个缩进单位。缩进的确切申明并未具体指定（空格 vs. 制表符）。一个制表符确切是8个空格（而非4个）。

=== 行长度（Line Length）
尽量避免一行的长度跨越80个字符，因为很多终端（特别是一些较老的终端）和对象处理方式不同，不便于阅读。

*注意：*用于文档中的例子应当应用更短的行长，长度一般不跨越70个字符。

=== 换行（Wrapping Lines）
当一个表达式无法容纳在一行内时，可以根据如下一般规矩断开之：

- 在一个逗号后面断开
- 在一个操纵符前面断开
- 宁可选择较高等别（higher-level）的断开，而非较初级别（lower-level）的断开
- 新的一行应当与上一行*同一级别*表达式的开首处对齐
- 若是以上规矩导致你的代码杂沓或者使你的代码都堆挤在右边，那就代之以缩进8个空格。

以下是断创方法调用的一些例子：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
someMethod(longExpression1, longExpression2, longExpression3,
        longExpression4, longExpression5);

var = someMethod1(longExpression1,
                someMethod2(longExpression2,
                        longExpression3));
----

以下是两个断开算术表达式的例子。前者更好，因为断开处位于括号表达式的外边，这是个较高等此外断开。
[source,java,indent=0]
[subs="verbatim,quotes"]
----
longName1 = longName2 * (longName3 + longName4 - longName5)
           + 4 * longname6; //PREFFER

longName1 = longName2 * (longName3 + longName4
                       - longName5) + 4 * longname6; //AVOID
----

以下是两个缩进方法声明的例子。前者是常规现象。后者若应用常规的缩进体式格式将会使第二行和第三行移得很靠右，所以代之以缩进8个空格
[source,java,indent=0]
[subs="verbatim,quotes"]
----
//CONVENTIONALINDENTATION
someMethod(int anArg, Object anotherArg, String yetAnotherArg,
           Object andStillAnother) {
    ...
}

//INDENT 8 SPACESTO AVOID VERY DEEP INDENTS
private static synchronized horkingLongMethodName(int anArg,
        Object anotherArg, String yetAnotherArg,
        Object andStillAnother) {
    ...
}
----

if语句的换行凡是应用8个空格的规矩，因为常规缩进（4个空格）会使语句体看起来斗劲费劲。比如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
//DON’T USE THISINDENTATION
if ((condition1&& condition2)
    || (condition3 && condition4)
    ||!(condition5 && condition6)) { //BAD WRAPS
    doSomethingAboutIt();            //MAKE THIS LINE EASY TO MISS
}

//USE THISINDENTATION INSTEAD
if ((condition1&& condition2)
        || (condition3 && condition4)
        ||!(condition5 && condition6))  {
    doSomethingAboutIt();
}

//OR USE THIS
if ((condition1&& condition2) || (condition3 && condition4)
        ||!(condition5 && condition6)) {
    doSomethingAboutIt();
}
----

这里有三种可行的方法用于处理长条件的三元运算表达式：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
alpha = (aLongBooleanExpression) ? beta : gamma;

alpha = (aLongBooleanExpression) ? beta
                                 : gamma;

alpha = (aLongBooleanExpression)
        ? beta
        : gamma;
----


== 注释（Comments）
Java程序有两类注释：编码注释（implementation comments）和文档注释（document comments）。编码注释是那些在C++中见过的，应用`/*...*/`和`//`界定的注释。文档注释（被称为"doc comments"）是Java独有的，并由`/**...*/`界定。文档注释可以经由过程javadoc对象转换成HTML文件。

编码注释用以注释代码或者实现细节。文档注释从实现（implementation-free）的角度描述代码的规范。它可以被那些手头没有源码的开发人员读懂。

注释应被用来给出代码的总括，并提供代码自身没有提供的附加信息。注释应当仅包含与浏览和读懂程序有关的信息。例如，响应的包如何被引用或位于哪个目录下之类的信息不该包含在注释中。

在注释里，对设计决定计划中首要的或者不是显而易见的地方进行申明是可以的，但应避免提供代码中己清楚表达出来的重复信息。多余的的注释很容易过期。总之应避免那些代码更新就可能过期的注释。

*注意：*频繁的注释有时反应出代码的低质量。当你感觉被迫要加注释的时候，推敲一下重写代码使其更清楚。

注释不该写在用星号或其他字符画出来的大框里。注释不该包含诸如制表符和回退符之类的特别字符。

=== 编码注释的结构（Implementation Comment Formats）
程序可以有4种编码注释的风格：块（block）、单行（single-line）、尾端（trailing）和行末（end-of-line）。

==== 块注释（Block Comments）
块注释一般用于提供对文件，方法，数据组织和算法的描述。块注释被置于每个文件的开端处以及每个方法之前。它们也可以被用于其他地方，比如方法内部。在函数和方法内部的块注释应当和它们所描述的代码具有一样的缩进结构。

块注释之首应当有一个空行，用于把块注释和代码分别开来，比如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
/*
 * Here is a block comment.
 */
----

块注释可以以`/*-`开始，如此`indent(1)`就可以将之辨认为一个代码块的开端，而不会重排它。
[source,java,indent=0]
[subs="verbatim,quotes"]
----
/*-
  * Here is ablock comment with some very special
  * formattingthat I want indent(1) to ignore.
  *
  *    one
  *        two
  *            three
  */
----

*注意：*若是你不应用indent(1)，就不必在代码中应用`/*-`，这样就能为他人可能对你的代码运行`indent(1)`作让步。参考"<<__documentation_comments,文档注释>>"

==== 单行注释（Single-Line Comments）

短注释可以显示在一行内，并与其后的代码具有一样的缩进层级。若是一个注释不能在一行内写完，就该采取块注释（参考"<<__block_comments,块注释>>"）。单行注释之前应当有一个空行。以下是一个Java代码中单行注释的例子：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
if （condition） {

    /* Handle thecondition. */
    ...
}
----


==== 尾端注释（Trailing Comments）

极短的注释可以与它们所要描述的代码位于同一行，而且应当有足够的空白来分隔代码和注释。如有多个短注释呈现于大段代码中，它们应当具有雷同的缩进。

以下是一个Java代码中尾端注释的例子：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
if (a == 2) {
    return TRUE;            /* Special case */
} else {}
    return isPrime(a);      / * Works only for odda */
}
----

==== 行末注释（End-Of-Line Comments）
注释界定符"`//`"，可以注释掉整行或者一行中的一项目组。它一般不用于连起多行的注释文本；然而，它可以用来注释掉连起多行的代码段。以下是所有三种风格的例子：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
if （foo > 1） {

    // Do adouble-flip.
    ...
}
else {
    return false;          // Explain why here.
}

//if （bar > 1）{
//
//    // Do a triple-flip.
//    ...
//}
//else {
//    return false;
//}
----

=== 文档注释（Documentation Comments）
*注意：*此处描述的注释组织示例，参考"<<_java_java_source_file_example,Java源文件示例>>"

若想理解更多，参考"How to Write Doc Comments for Javadoc"，此中包含了有关文档注释标识表记标帜的信息（`@return`， `@param`， `@see`）：

http://java.sun.com/javadoc/writingdoccomments/index.html

若想理解更多有关文档注释和javadoc的具体材料，参考javadoc的主页：

http://java.sun.com/javadoc/index.html

文档注释描述Java的类、接口、构造器、方法、以及字段（field）。每个文档注释都应被置于注释定界符`/**...*/`之中，一个注释对应一个类、接口或成员。该注释应位于声明之前：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
/**
 * The Exampleclass provides ...
 */
public classExample { ...
----
*注意：*顶层（top-level）的类和接口是不缩进的，而其成员是缩进的。描述类和接口的文档注释的第一行（``）不需缩进；随后的文档注释每行都缩进1格（使星号纵向对齐）。成员，包含构造函数在内，其文档注释的第一行缩进4格，随后每行都缩进5格。

若你想给出有关类、接口、变量或方法的信息，而这些信息又不合适写在文档中，则可应用实现块注释（见5.1.1）或紧跟在声明后面的单行注释（见5.1.2）。例如，有关一个类实现的细节，应放入紧跟在类声明后面的实现块注释中，而不是放在文档注释中。

文档注释不应该放在一个方法或构造器的定义块中，因为Java会将位于文档注释之后的第一个声明与其相关联。


== 声明（Declarations）
=== 每行声明变量的数量（Number Per Line）
推荐一行一个声明，因为这样有利于写注释。亦即，
[source,java,indent=0]
[subs="verbatim,quotes"]
----
int level;  // indentation level
int size;   // size of table
----
要优于，
[source,java,indent=0]
[subs="verbatim,quotes"]
----
int level， size;
----
不要将不合类型变量的声明放在同一行，例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
int foo,  fooarray[];  //WRONG!
----
*注意：*上方的例子中，在类型和标识符之间放了一个空格，另一种被容许的转换式格式是用的制表符：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
int          level;         // indentation level
int          size;          // size of table
Object       currentEntry;  // currently ed table entry
----

=== 初始化（Initialization）
尽量在声明局部变量的同时初始化。唯一不这么做的来由是变量的初始值依附于某些先前产生的运行值。

=== 组织（Placement）
只在代码块的开端处声明变量。（一个块是指任何被包含在大括号"`{`"和"`}`"中心的代码。）不要在初次用到该变量时才声明之。这会把注意力不集中的程序员搞糊涂，同时会影响代码在该作用域内的可移植性。

[source,java,indent=0]
[subs="verbatim,quotes"]
----
void myMethod（） {
    int int1 = 0;         // beginning of method block

    if （condition） {
        int int2 = 0;     // beginning of "if"block
        ...
    }
}
----
该规矩的一个例外是for循环的索引变量
[source,java,indent=0]
[subs="verbatim,quotes"]
----
for （int i = 0; i < maxLoops; i++） { ... }
----
避免声明的局部变量覆盖上一级声明的变量。例如，不要在内部代码块中声明雷同的变量名：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
int count;
...
myMethod（） {
    if （condition） {
        int count= 0;     // AVOID!
        ...
    }
    ...
}
----

=== 类和接口的声明（Class and Interface Declarations）
当编写类和接口时，应当遵守以下组织规矩：

- 在方法名与其参数列表之前的左括号"`(`"间不要有空格
- 左大括号"`{`"位于声明语句同业的末尾
- 右大括号"`}`"另起一行，与响应的声明语句对齐，除非是一个空语句，"`}`"应紧跟在"`{`"之后
- 方法与方法之间以空行分隔

[source,java,indent=0]
[subs="verbatim,quotes"]
----
class Sample extends Object {
    int ivar1;
    int ivar2;

    Sample(int i, int j) {
        ivar1 = i;
        ivar2 = j;
    }

    int emptyMethod() {}

    ...
}
----


== 语句（Statements）
=== 简单语句（Simple Statements）
每行至多包含一条语句，例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
argv++;       // Correct
argc--;       // Correct
argv++; argc--;       // AVOID!
----

=== 复合语句（Compound Statements）
复合语句是包含在大括号中的语句序列，形如"`{ 语句 }`"。例如下面各段。

-  被括此中的语句应当较之复合语句缩进一个层次
- 左大括号"{"应位于复合语句判断行的行尾；右大括号"}"应另起一行并与复合语句首行对齐。
- 大括号可以被用于所有语句，包含单个语句，只要这些语句是诸如if-else或for把握组织的一项目组。这样便于添加语句而无需担心因为忘了加括号而引起bug。

=== 返回语句（return Statements）
if-else语句应当具有如下结构：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
if (condition) {
    statements;
}

if (condition) {
    statements;
} else {
    statements;
}

if (condition) {
    statements;
} else if (condition) {
    statements;
} else {
    statements;
}
----
*注意：*if语句老是用"{"和"}"括起来，避免应用如下轻易引起错误的组织：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
if (condition)//AVOID! THIS OMITS THE BRACES {}!
    statement;
----

=== for语句（for Statements）
一个for语句应当具有如下结构：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
for (initialization; condition; ) {
    statements;
}
----
一个空的for语句（所有工作都在初始化，前提断定，更新子句中完成）应当具有如下结构：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
for （initialization; condition; ）;
----
当在for语句的初始化或更新子句中应用逗号时，避免因应用三个以上变量，而导致错杂度进步。若须要，可以在for循环之前（为初始化子句）或for循环末尾（为更新子句）应用零丁的语句。

===  while语句（while Statements）
一个while语句应当具有如下结构：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
while (condition) {
    statements;
}
----
一个空的while语句应当具有如下结构：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
while (condition);
----

=== do-while语句（do-while Statements）
一个do-while语句应当具有如下结构：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
do {
    statements;
} while (condition);
----

=== switch语句（switch Statements）
一个switch语句应当具有如下结构：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
switch (condition) {
case ABC:
    statements;
    /* falls through */
case DEF:
    statements;
    break;

case XYZ:
    statements;
    break;

default:
    statements;
    break;
}
----
每当一个`case`顺着往下履行时（因为没有`break`语句），这时就应在`break`语句的地位添加注释。上方的示例代码中就包含注释`/* falls through */`。

=== try-catch语句（try-catch Statements）
一个`try-catch`语句应当具有如下结构：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
try {
    statements;
} catch (ExceptionClass e) {
    statements;
}
----
一个`try-catch`语句后面也可能跟着一个`finally`语句，无论`try`代码块是否顺利执行完，它都会被执行。
[source,java,indent=0]
[subs="verbatim,quotes"]
----
try {
    statements;
} catch (ExceptionClass e) {
    statements;
} finally {
    statements;
}
----


== 空白（White Space）
=== 空行（Blank Lines）
空行将逻辑相干的代码段分隔开，以增强可读性。

下列景象应当总是应用两个空行：

- 一个源文件的两个片段（section）之间
- 类声明和接口声明之间

下列景象应当总是应用一个空行：

- 两个方法之间
- 方法内的局部变量和方法的第一条语句之间
- 块注释（参考"5.1.1"）或单行注释（参考"5.1.2"）之前
- 一个方法内的两个逻辑段之间，用以增强可读性

=== 空格（Blank Spaces）
下列场景应当应用空格：

- 一个紧跟着括号的关键字应当被空格分隔，例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
while (true) {
     ...
}
----
*注意：*空格不该该置于方法名与其左括号之间。这将有助于区分关键字和方法调用。

- 参数列表中逗号的后面应当有一个空格
- 所有的二元运算符，除了"`.`"，应当应用空格将之与操纵数分隔。一元操纵符和操纵数之间不因该加空格，比如：负号（"-"）、自增（"++"）和自减（"--"）。例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
a += c + d;
   a = (a + b) / (c * d);

   while (d++ = s++) {
       n++;
   }
   printSize("size is " + foo + ".");
----
- for语句中的表达式应当被空格分隔，例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
for (expr1; expr2; expr3)
----
- 强迫转型后应当跟一个空格，例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
myMethod((byte) aNum, (Object) x);
    myMethod((int) (cp + 5), ((int) (i + 3))
                                  + 1);
----


== 命名规范（Naming Conventions）
命名规范使程序更易读，从而更易于理解。它们也可以提供一些有关标识符功能的信息，以助于理解代码，例如，无论它是一个常量，包，还是类。
[cols="1,4,2",options="header"]
|===
|标识符类型  |定名规矩 |例子
|包（Packages） |一个独一包名的前缀老是全部小写的ASCII字母并且是一个域名，凡是是com，edu，gov，mil，net，org，或1981年 ISO 3166标准所指定的标识国度的英文双字符代码。包名的后续项目组按照不合机构各自内部的命名规范而不尽雷同。这类命名规范可能以特定目录名的构成来区分部 门（department），项目（project），机械（machine），或注册名（login names）。 |com.sun.eng com.apple.quicktime.v2 edu.cmu.cs.bovik.cheese
|类（Classes） |定名规矩：类名是个一名词，采取大小写混淆的体式格式，每个单词的首字母大写。尽量使你的类名简洁而富于描述。应用完全单词，避免缩写词（除非该缩写词被更广泛应用，像URL，HTML） |class Raster; class ImageSprite;
|接口（Interfaces） |定名规矩：大小写规矩与类名类似 |interface RasterDelegate; interface Storing;
|方法（Methods） |方法名是一个动词，采取大小写混淆的体式格式，第一个单词的首字母小写，厥后单词的首字母大写。 |run(); runFast(); getBackground();
|变量（Variables） |除了变量名外，所有实例，包含类，类常量，均采取大小写混淆的体式格式，第一个单词的首字母小写，厥后单词的首字母大写。变量名不该以下划线或美元符号开首，尽管这在语法上是容许的。
变量名应简短且富于描述。变量名的选用应当易于记忆，即，可以或许指出其用处。尽量避免单个字符的变量名，除非是一次性的姑且变量。姑且变量凡是被取名为i，j，k，m和n，它们一般用于整型；c，d，e，它们一般用于字符型。 |char c; int i; float myWidth;
|实例变量（Instance Variables） |大小写规矩和变量名类似，除了前面须要一个下划线 |int _employeeId; String _name; Customer _customer;
|常量（Constants） |类常量和ANSI常量的声明，应当全部大写，单词间用下划线隔开。（尽量避免ANSI常量，轻易引起错误） |static final int MIN_WIDTH = 4; static final int MAX_WIDTH = 999; static final int GET_THE_CPU = 1;
|===


== 编程实践（Programming Practices）
=== 提供对实例以及类变量的访问（Providing Access to Instance and Class Variables）
若没有足够来由，不要把实例或类变量声明为公有。凡是，实例变量无需显式的设置（set）和获取（gotten），这作为是方法调用的边沿效应 （side effect）而产生。

一个具有公有实例变量的恰当例子，是类仅作为数据结构，没有行为。亦即，若你要应用一个结构（struct）而非一个类（若是java支撑结构的话），那么把类的实例变量声明为公有是合适的。

=== 引用类变量和类方法（Referring to Class Variables and Methods）
避免用一个对象调用一个类的静态变量和方法。应当用类名调换。例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
classMethod();             //OK
AClass.classMethod();      //OK
anObject.classMethod();    //AVOID!
----

=== 常量（Constants）
位于for循环中作为计数器值的数字常量，除了-1，0和1之外，不该被直接写入代码。

=== 变量赋值（Variable Assignments）
避免在一个语句中给多个变量赋雷同的值。它很难读懂。例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
fooBar.fChar = barFoo.lchar = "c"; // AVOID!
----
不要将赋值运算符用在轻易与相等关系运算符混合的地方。例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
if (c++ = d--) {        // AVOID! （Java disallows）
    ...
}
----
应当写成
[source,java,indent=0]
[subs="verbatim,quotes"]
----
if ((c++ = d--) != 0) {
    ...
}
----
不要应用内嵌（embedded）赋值运算符试图进步运行时的效力，这是编译器的工作。例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
d = （a = b + c） + r;        // AVOID!
----
应当写成
[source,java,indent=0]
[subs="verbatim,quotes"]
----
a = b + c;
d = a + r;
----

=== 其它实战（Miscellaneous Practices）
====  圆括号（Parentheses）
一般而言，在含有多种运算符的表达式中应用圆括号来强调运算符优先级，是个好方法。即使运算符的优先级对你而言可能很清楚，但对其他人未必如此。你不如假设此外程序员和你一样清楚运算符的优先级。
[source,java,indent=0]
[subs="verbatim,quotes"]
----
if (a == b && c == d)      // AVOID!
if ((a == b) && (c == d))  // RIGHT
----

==== 返回值（Returning Values）
设法让你的程序组织符合目标。例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
if （booleanExpression） {
    return true;
} else {
    return false;
}
----
应当代之以如下方法：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
return booleanExpression;
----
类似地：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
if （condition） {
    return x;
}
return y;
----
应当写做：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
return （condition ？ x : y）;
----

==== 前提运算符"?"前的表达式（Expressions before "?" in the Conditional Operator）
若是一个包含二元运算符的表达式呈如今三元运算符"` ? : `"的"?"之前，那么应当给表达式添上一对圆括号。例如：
[source,java,indent=0]
[subs="verbatim,quotes"]
----
(x >= 0) ? x : -x;
----

==== 特别注释（Special Comments）
在注释中应用`XXX`来标识某些未实现（bogus）的但可以工作（works）的内容。用`FIXME`来标识某些假的和错误的内容。


== 代码示例（Code Examples）
=== Java源文件示例（Java Source File Example）
下面的例子，显现了如何合理组织一个包含单一公共类的Java源程序。接口的结构与其类似。更多信息参考"<<__class_and_interface_declarations,类和接口声明>>"以及"<<_documentation_comments,文挡注释>>"。
[source,java,indent=0]
[subs="verbatim,quotes"]
----
/*
 * @(#)Blah.java        1.82 99/03/18
 *
 * Copyright (c)1994-1999 Sun Microsystems， Inc.
 * 901 San AntonioRoad， Palo Alto， California， 94303， U.S.A.
 * All rightsreserved.
 *
 * This software isthe confidential and proprietary information of Sun
 * Microsystems，Inc. ("Confidential Information"). You shall not
 * disclose suchConfidential Information and shall use it only in
 * accordance withthe terms of the license agreement you entered into
 * with Sun.
 */


package java.blah;

import java.blah.blahdy.BlahBlah;

/**
 * Classdescription goes here.
 *
 * @version    1.82 18 Mar 1999
 * @author     Firstname Lastname
 */
public class Blah extends SomeClass {
    /* A classimplementation comment can go here. */

    /** classVar1documentation comment */
    public staticint classVar1;

    /**
     * classVar2documentation comment that happens to be
     * more thanone line long
     */
    private static ObjectclassVar2;

    /**instanceVar1 documentation comment */
    public ObjectinstanceVar1;

    /**instanceVar2 documentation comment */
    protected intinstanceVar2;

    /**instanceVar3 documentation comment */
    privateObject[] instanceVar3;

    /**
     *...constructor Blah documentation comment...
     */
    public Blah() {
        //...implementation goes here...
    }

    /**
     * ...methoddoSomething documentation comment...
     */
    public voiddoSomething() {
        //...implementation goes here...
    }

    /**
     * ...methoddoSomethingElse documentation comment...
     * @paramsomeParam description
     */
    public voiddoSomethingElse(Object someParam) {
        //...implementation goes here...
    }
}
----
